stages:
  - test

test:
  stage: test
  image: ubuntu:20.04
  before_script:
    - sudo apt-get install libpq-dev libgmp-dev libmpfr-dev libmpc-dev
    - pip install -r requirements.txt
  script:
    - echo hello world

  services:
    - postgres

  variables:
    PGUSER: zeus
    PGHOST: postgres
    POSTGRES_DB: zeus
    POSTGRES_USER: zeus
    POSTGRES_PASSWORD: ''
    POSTGRES_HOST_AUTH_METHOD: trust
