stages:
  - test

pytest:
  stage: test
  image: ubuntu:20.04
  before_script:
    - apt-get -y update
    - apt-get -y install libpq-dev libgmp-dev libmpfr-dev libmpc-dev
        python3-dev python3-venv python3-pip gettext
    - python3 -m venv env/
    - ./env/bin/pip install -r requirements.txt
    - env
  script:
    - source ./env/bin/activate
    - ./compile-translations.sh
    - pytest -v --cov -n 2
    - codecov

  services:
    - postgres

  variables:
    DEBIAN_FRONTEND: noninteractive
    PGUSER: zeus
    PGHOST: postgres
    POSTGRES_DB: zeus
    POSTGRES_USER: zeus
    POSTGRES_PASSWORD: ''
    POSTGRES_HOST_AUTH_METHOD: trust

flake8:
  stage: test
  image: ubuntu:20.04
  before_script:
    - apt-get -y update
    - apt-get -y install python3-pip
    - python3 -m pip install flake8==3.9.1
  script:
    - flake8 --config=.flake8
