language: python
python:
  - "3.8"
cache: pip
services:
  - postgresql

env:
  global:
    - PGUSER=travis

install:
  - sudo apt-get install libpq-dev libgmp-dev libmpfr-dev libmpc-dev
  - sudo -u postgres createuser -s travis || true
  - createdb zeus
  - pip install -r requirements.txt

jobs:
  include:
    - name: flake8
      install:
        pip install flake8==3.9.1
      services: []
      script:
        - flake8 --config=.flake8
    - name: pytest
      script:
        - ./compile-translations.sh
        - pytest -v --cov -n 2
      after_success:
        - codecov
