version: "3.7"
services:
  redis:
    image: redis:latest

  prod:
    command: uwsgi --master --ini uwsgi.ini --die-on-term
    ports:
      - "8000:8000"

    build:
      context: .
      target: zeus_prod

    volumes:
      - ./data:/home/user/zeus/data:rw
    working_dir: /home/user/zeus
    environment:
      - DJANGO_SETTINGS_MODULE=${ZEUS_PROD_SETTINGS}
      - ZEUS_PROD_SECRET_KEY
      - ZEUS_PROD_HOST
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_USE_TLS
      - EMAIL_USE_SSL

      - PGHOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    depends_on:
      - redis

  prod_celery:
    command: celery -A zeus.celery worker -l INFO --concurrency 1 --pool solo

    build:
      context: .
      target: zeus_prod

    volumes:
      - ./data:/home/user/zeus/data:rw
    working_dir: /home/user/zeus
    environment:
      - DJANGO_SETTINGS_MODULE=${ZEUS_PROD_SETTINGS}
      - ZEUS_PROD_SECRET_KEY
      - ZEUS_PROD_HOST
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_USE_TLS
      - EMAIL_USE_SSL

      - PGHOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    depends_on:
      - redis
