version: "3.7"
networks:
  default:
  traefik:
    external: true
    name: traefik
services:
  redis:
    image: redis:latest
    restart: unless-stopped

  prod:
    command: uwsgi --master --ini uwsgi.ini --die-on-term
    restart: unless-stopped
    #ports:
    #- "8094:8000"
    expose:
      - 8000
    build:
      context: .
      target: zeus_prod

    volumes:
      - ./data:/home/user/zeus/data:rw
    networks:
      - default
      - traefik
    working_dir: /home/user/zeus
    labels:
      - environment=prod
      - traefik.enable=true
      - traefik.http.routers.${ROUTER_NAME}.rule=Host("${ZEUS_PROD_HOST}","www.${ZEUS_PROD_HOST}")
      - traefik.http.services.${ROUTER_NAME}.loadbalancer.server.port=8000
    environment:
      - DJANGO_SETTINGS_MODULE=${ZEUS_PROD_SETTINGS}
      - ZEUS_PROD_SECRET_KEY
      - ZEUS_PROD_HOST
      - ZEUS_PROD_USE_HTTPS
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_USE_TLS
      - EMAIL_USE_SSL

      - PGHOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    depends_on:
      - redis

  prod_celery:
    restart: unless-stopped
    command: celery -A zeus.celery worker -l INFO --concurrency 2 -P solo -f /home/user/zeus/data/celery.log

    build:
      context: .
      target: zeus_prod

    volumes:
      - ./data:/home/user/zeus/data:rw
    working_dir: /home/user/zeus
    environment:
      - DJANGO_SETTINGS_MODULE=${ZEUS_PROD_SETTINGS}
      - ZEUS_PROD_SECRET_KEY
      - ZEUS_PROD_HOST
      - ZEUS_PROD_USE_HTTPS
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_HOST_USER
      - EMAIL_HOST_PASSWORD
      - EMAIL_USE_TLS
      - EMAIL_USE_SSL

      - PGHOST
      - PGDATABASE
      - PGUSER
      - PGPASSWORD
    depends_on:
      - redis
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_DB: ${PGDATABASE}
    volumes:
      - ./volumes/pgdata:/var/lib/postgresql/data